INSERT OR IGNORE INTO kernels VALUES
    ('softmax', 'Softmax (Online 2-pass)', 'activation',
     'Row-wise softmax: 2-pass online algorithm (Milakov & Gimelshein 2018). Fused max+exp+sum in pass 1, normalize in pass 2.',
     'templates/softmax_batch.metal', datetime('now')),
    ('layernorm', 'Layer Normalization', 'normalization',
     '3-pass fused LayerNorm: mean, variance, normalize+affine. Single workgroup per row.',
     'templates/layernorm_batch.metal', datetime('now')),
    ('matmul', 'Matrix Multiplication (GEMM)', 'linear_algebra',
     'Dense C = A @ B. Tiled with shared memory, the fundamental ML primitive.',
     NULL, datetime('now')),
    ('vq-quantize', 'VQ Quantize + EMA Update', 'quantization',
     'Fused L2 distance argmin + atomic scatter-add for codebook EMA update. Used in VQ-VAE training.',
     'templates/vq_l2dist_argmin.metal', datetime('now')),
    ('conv1d-dilated', 'Dilated Conv1D + ReLU', 'convolution',
     'Fused dilated 1D convolution (kernel=3) + bias + ReLU. Eliminates pad+gather+concat intermediate buffers.',
     'templates/dilated_conv1d_relu.metal', datetime('now')),
    ('scatter-add', 'Atomic Scatter-Add', 'reduction',
     'Atomic float scatter-add for EMA codebook updates. Tests atomic throughput.',
     'templates/ema_scatter_add.metal', datetime('now')),
    ('triple-head-argmax', 'Triple-Head Fused Argmax', 'decode',
     'Fused 3-head matmul + bias + argmax without materializing (B, vocab) logit tensors.',
     'templates/triple_head_argmax.metal', datetime('now')),
    ('l1-smooth-loss', 'L1 Smooth (Huber) Loss', 'loss',
     'Masked smooth-L1 loss for reconstruction training. Tests scalar reduction efficiency.',
     NULL, datetime('now')),
    ('vec-add', 'Vector Addition', 'elementwise',
     'Element-wise addition baseline. Measures raw memory bandwidth.',
     NULL, datetime('now')),
    ('attention', 'Scaled Dot-Product Attention', 'attention',
     'Q @ K^T / sqrt(d) → softmax → @ V. The core transformer primitive.',
     NULL, datetime('now')),
    ('gelu', 'GELU Activation', 'activation',
     'Gaussian Error Linear Unit. Tests transcendental function throughput.',
     NULL, datetime('now')),
    ('rms-norm', 'RMS Normalization', 'normalization',
     'Root Mean Square normalization (used in LLaMA, Gemma). Simpler than LayerNorm.',
     NULL, datetime('now'));
