INSERT OR IGNORE INTO kernels VALUES
    ('softmax', 'Softmax (Online 2-pass)', 'activation',
     'Row-wise softmax: 2-pass online algorithm (Milakov & Gimelshein 2018). Fused max+exp+sum in pass 1, normalize in pass 2.',
     'templates/softmax_batch.metal', datetime('now')),
    ('layernorm', 'Layer Normalization', 'normalization',
     '3-pass fused LayerNorm: mean, variance, normalize+affine. Single workgroup per row.',
     'templates/layernorm_batch.metal', datetime('now')),
    ('matmul', 'Matrix Multiplication (GEMM)', 'linear_algebra',
     'Dense C = A @ B. Tiled with shared memory, the fundamental ML primitive.',
     NULL, datetime('now')),
    ('vq-quantize', 'VQ Quantize + EMA Update', 'quantization',
     'Fused L2 distance argmin + atomic scatter-add for codebook EMA update. Used in VQ-VAE training.',
     'templates/vq_l2dist_argmin.metal', datetime('now')),
    ('conv1d-dilated', 'Dilated Conv1D + ReLU', 'convolution',
     'Fused dilated 1D convolution (kernel=3) + bias + ReLU. Eliminates pad+gather+concat intermediate buffers.',
     'templates/dilated_conv1d_relu.metal', datetime('now')),
    ('scatter-add', 'Atomic Scatter-Add', 'reduction',
     'Atomic float scatter-add for EMA codebook updates. Tests atomic throughput.',
     'templates/ema_scatter_add.metal', datetime('now')),
    ('triple-head-argmax', 'Triple-Head Fused Argmax', 'decode',
     'Fused 3-head matmul + bias + argmax without materializing (B, vocab) logit tensors.',
     'templates/triple_head_argmax.metal', datetime('now')),
    ('l1-smooth-loss', 'L1 Smooth (Huber) Loss', 'loss',
     'Masked smooth-L1 loss for reconstruction training. Tests scalar reduction efficiency.',
     NULL, datetime('now')),
    ('vec-add', 'Vector Addition', 'elementwise',
     'Element-wise addition baseline. Measures raw memory bandwidth.',
     NULL, datetime('now')),
    ('attention', 'Scaled Dot-Product Attention', 'attention',
     'Q @ K^T / sqrt(d) → softmax → @ V. The core transformer primitive.',
     NULL, datetime('now')),
    ('gelu', 'GELU Activation', 'activation',
     'Gaussian Error Linear Unit. Tests transcendental function throughput.',
     NULL, datetime('now')),
    ('rms-norm', 'RMS Normalization', 'normalization',
     'Root Mean Square normalization (used in LLaMA, Gemma). Simpler than LayerNorm.',
     NULL, datetime('now')),
    ('causal-mask', 'Causal Mask', 'masking',
     'Set upper triangle of attention scores to -inf. Required for autoregressive (decoder) attention.',
     NULL, datetime('now')),
    ('cross-entropy', 'Cross-Entropy Loss', 'loss',
     'Numerically stable -logits[target] + log-sum-exp(logits). Standard LM training loss.',
     NULL, datetime('now')),
    ('embedding', 'Embedding Lookup', 'memory_access',
     'Gather rows from a (V, D) weight table by token indices. First op of every transformer.',
     NULL, datetime('now')),
    ('rope', 'Rotary Position Embedding', 'positional_encoding',
     'Rotate Q/K dimension pairs by frequency-dependent angles (Su et al. 2021). Used in LLaMA, Mistral, Qwen, etc.',
     NULL, datetime('now')),
    ('silu', 'SiLU / Swish', 'activation',
     'x * sigmoid(x). Gate activation in LLaMA/Mistral FFN blocks.',
     NULL, datetime('now')),
    ('deepseek_decode_step', 'DeepSeek Decode Step', 'decode',
     'One autoregressive decode step of DeepSeek-R1-Distill-Qwen-1.5B (28 layers, 1536 hidden, GQA 12h/2kv, 17920 FFN). End-to-end latency of per-token compute.',
     NULL, datetime('now')),
    ('rms_norm_1536', 'RMS Norm (D=1536)', 'normalization',
     'Hidden-dim RMS normalization for the 1.5B DeepSeek model. Commonly fused with residual add.',
     NULL, datetime('now')),
    ('attention_decode_gqa', 'GQA Attention (decode)', 'attention',
     'Grouped-query attention for decode step: 12 Q-heads, 2 KV-heads, head_dim=128. One new token vs KV cache.',
     NULL, datetime('now')),
    ('attention_1head_cpp', 'Single-Head Attention (cpp-tile)', 'attention',
     'Per-head custom AscendC tile kernel for GQA decode. Drives 18× speedup via vectorized matvec emitter.',
     NULL, datetime('now')),
    ('q_proj_matvec', 'Q Projection Matvec', 'linear_algebra',
     'Decode Q projection: [1,1536] @ [1536,1536]. Per-layer matvec.',
     NULL, datetime('now')),
    ('kv_proj_matvec', 'KV Projection Matvec (fused)', 'linear_algebra',
     'Fused K+V projection: [1,1536] @ [1536,512]. GQA with 2 KV heads × 128 head_dim × 2 (K+V).',
     NULL, datetime('now')),
    ('mlp_gate_up_silu', 'MLP Gate+Up+SiLU (fused)', 'activation',
     'Fused gate and up projection [1,1536] @ [1536,17920] + SiLU gate activation. Qwen-style SwiGLU FFN.',
     NULL, datetime('now')),
    ('down_proj_residual', 'MLP Down Projection + Residual', 'linear_algebra',
     'Down projection [1,8960] @ [8960,1536] fused with residual add.',
     NULL, datetime('now')),
    ('argmax_greedy', 'Greedy Argmax over Vocab', 'decode',
     'Argmax over logits of shape [1, 151936]. Final step of greedy decode. Fused with LM head in some impls.',
     NULL, datetime('now')),
    ('qkvo_matvecs', 'QKVO Matvec Bundle', 'linear_algebra',
     'Q + K + V + O projection matvecs for one transformer block. Bandwidth-dominated per-token decode workload.',
     NULL, datetime('now')),
    ('rope_qk_decode', 'RoPE apply to Q/K (decode)', 'positional_encoding',
     'Apply rotary position embedding to decoded Q and K vectors. Small but frequently fused.',
     NULL, datetime('now'));
